name: Submit Review
on:
  repository_dispatch:
    types: [submit-review]

jobs:
  add-comment:
    runs-on: ubuntu-latest
    steps:
      - name: Create Issue Comment
        uses: peter-evans/create-or-update-comment@v3
        with:
          token: ${{ secrets.GH_REVIEW_TOKEN }}
          issue-number: ${{ github.event.client_payload.issue }}
          body: ${{ github.event.client_payload.review }}
